# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import qna.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_kind', enumchoicefield.fields.EnumChoiceField(enum_class=qna.models.Enum_Kind, max_length=2)),
                ('owner', models.CharField(max_length=20, null=True, verbose_name='Owner.')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject.')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('answer', models.TextField(null=True, verbose_name='Answer.')),
                ('attach', models.FileField(blank=True, upload_to='uploads/qna/%Y/%m/%d/', verbose_name='Attachment.')),
                ('passno', models.CharField(help_text='Required. 4 digits Only.', max_length=4, null=True, verbose_name='Password.')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('buz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.Company')),
            ],
            options={
                'verbose_name_plural': 'qnas',
                'db_table': 'qna',
                'ordering': ['-mdate'],
            },
        ),
    ]
